const quotes = [
"Small progress is still progress.",
"Focus on the step in front of you, not the whole staircase.",
"Discipline creates the results motivation talks about.",
"One focused session can change your whole day.",
"Your future self will thank you for studying today.",
"Consistency beats intensity when it comes to learning.",
"Start where you are. Use what you have. Do what you can.",
"The best study session is the one you actually begin.",
"You do not need more time. You need more focus.",
"Stay patient. Real progress takes repeated effort.",
"A calm mind learns better.",
"Focus is your superpower in a distracted world.",
"Do the work even when you don’t feel like it.",
"Focus on progress, not perfection.",
"One hour of deep work beats five hours of distraction.",
"Your habits decide your future.",
"Stay consistent. Results will follow.",
"Distraction is the enemy of progress.",
"Build discipline, and motivation will follow.",
"Work in silence, let results speak.",
"Every focused minute counts.",
"Clarity comes from action, not overthinking.",
"Don’t wait for motivation. Create it through action.",
"Small efforts repeated daily lead to big results.",
"Deep focus creates real growth.",
"Show up, even on the days you don’t feel like it.",
"Effort today builds confidence tomorrow.",
"Your goals don’t care about your mood.",
"Focus now, relax later.",
"Time you invest in learning always pays off.",
"Keep going. You’re closer than you think.",
"The difference between success and failure is consistency.",
"Train your mind to stay where your body is.",
"Less scrolling, more studying.",
"Turn off distractions. Turn on your potential.",
"Discipline is choosing what you want most over what you want now.",
"Your attention is your most valuable resource.",
"Great results come from focused effort.",
"Every session is a step forward.",
"Stay locked in. It’s worth it.",
"Focus creates freedom.",
"Do it tired. Do it unmotivated. Just do it.",
"Consistency builds confidence.",
"Make your future self proud.",
"Focus is a skill. Train it daily.",
"Stop thinking. Start doing.",
"Success is built in quiet, focused moments."
];

export function getRandomQuote() {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}